Python_Cats_prj/urls.py
from django.conf.urls import url, include
# from django.contrib import admin

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^cats/', include('apps.cats.urls', namespace='cats')),
    # url(r'users/(?P<userId>\d+)/cats/', include('apps.cats.urls', namespace='user_cats')),
    url(r'^',include('apps.users.urls',namespace='users')),
]

apps/cats/urls.py
from django.conf.urls import url
from . import views
import logging
logging.basicConfig(level=logging.DEBUG,
                    format='%(asctime)s - %(levelname)s - %(message)s')


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^new/$', views.new, name='new'),
    url(r'^create/$', views.create, name='create'),
    url(r'^(?P<objId>\d+)/$', views.show, name='show'),
    url(r'^(?P<objId>\d+)/edit/$', views.edit, name='edit'),
    url(r'^(?P<objId>\d+)/update/$', views.update, name='update'),
    url(r'^(?P<objId>\d+)/destroy/$', views.destroy, name='destroy'),
    url(r'^(?P<objId>\d+)/like/$', views.create_like, name='create_like'),
    url(r'^(?P<objId>\d+)/like/destroy$', views.destroy_like, name='destroy_like'),
]

apps/cats/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from ..users.models import User
from .error import Error
import isvalid

import logging
logging.basicConfig(level=logging.DEBUG,
                    format='%(asctime)s - %(levelname)s - %(message)s')

# Create your models here.
class CatManager(models.Manager):
    # @property
    # def likes_count(self):
    #     return self.likes.count()
    def validate_cat(self, data):
        errors = []
        if 'name' in data and 'age':
            valid, msg = isvalid.name(data['name'])
            if not valid:
                errors.append(Error('name', msg))
            valid, msg = isvalid.age(data['age'])
            if not valid:
                errors.append(Error('age', msg))
        else:
            errors.append(
                Error('form', 'Something went wrong please try to submit the form again'))
        if errors:
            return (False, errors)
        else:
            return (True, data)
    def add_cat(self, data, user):
        logging.debug('add cat')
        valid, errors = self.validate_cat(data)
        logging.debug(errors)
        if valid:
            cat_data = {'name': data['name'],
                        'age': data['age'],
                        'user': user}
            return (valid, self.create(**cat_data))
        else:
            return (valid, errors)

    def update_cat(self, cat, data):
        logging.debug('update cat')
        valid, errors = self.validate_cat(data)
        logging.debug(errors)
        if valid:
            cat.name = data['name']
            cat.age = data['age']
            cat.save()
            return (valid, cat)
        else:
            return (valid, errors)




class Cat(models.Model):
    objects = CatManager()
    name = models.CharField(max_length=100)
    age = models.IntegerField()
    user = models.ForeignKey(User,on_delete=models.CASCADE, related_name='cats')
    likes = models.ManyToManyField(User, related_name='users')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '%s: %s %s %s %s' % (self.id, self.name, self.age, self.user, self.likes.count())

    def __unicode__(self):
        return '%s: %s %s %s %s' % (self.id, self.name, self.age, self.user, self.likes.count())


# TODO: Create a seperate app to track likes it seems like a common ask

apps/cats/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect, HttpResponse
from django.core.urlresolvers import reverse, resolve
from django.contrib import messages
from django.db.models import Count
from models import Cat
from ..users.models import User
from ..users.decorators import user_login_required, user_passes_test
import base64

import logging
logging.basicConfig(level=logging.DEBUG,
                    format='%(asctime)s - %(levelname)s - %(message)s')


# Create your views here.
@user_login_required
def index(request):
    logging.debug('%s.%s - %s' % (request.resolver_match.namespaces,
                                  request.resolver_match.func.__name__, request.path))
    user = User.objects.logged_in(request.session)
    cats = Cat.objects.all().annotate(
        likes_count=Count('likes')).order_by('-likes_count')
    context = {'user': user,
               'cats': cats}
    return render(request, 'cats/list_cats.html', context)

@user_login_required
def new(request):
    logging.debug('%s.%s - %s' % (request.resolver_match.namespaces,
                                  request.resolver_match.func.__name__, request.path))
    user = User.objects.logged_in(request.session)
    if user:
        return render(request, 'cats/new_cat.html')
    else:
        # if not logged in send to login page with next page to go to after login
        next_pg = base64.urlsafe_b64encode(request.path)
        return redirect(reverse('users:disp_login') + '?next=%s' % (next_pg))

# Need to figure out what we cannot use reverse routes for next_url
@user_login_required(next_url='/cats/new/')
def create(request):
    """Creates the Object"""
    logging.debug('%s.%s - %s' % (request.resolver_match.namespaces,
                                  request.resolver_match.func.__name__, request.path))
    user = User.objects.logged_in(request.session)
    valid, data = Cat.objects.add_cat(request.POST, user)
    logging.debug(data)
    if valid:
        return redirect(reverse('cats:index'))
    else:
        for i in data:
            messages.add_message(request, messages.ERROR, i.message)
        return redirect(reverse('cats:new'))
    # can we do this better
    return redirect(reverse('cats:index'))

@user_login_required
def show(request, objId):
    """Shows a specific Object"""
    logging.debug('%s.%s - %s' % (request.resolver_match.namespaces,
                                  request.resolver_match.func.__name__, request.path))
    user = User.objects.logged_in(request.session)
    if user:
        context = {'user': user,
                   'cat': Cat.objects.get(id=objId), }
        return render(request, 'cats/show_cat.html', context)
    else:
        # if not logged in send to login page with next page to go to after login
        next_pg = base64.urlsafe_b64encode(request.path)
        return redirect(reverse('users:disp_login') + '?next=%s' % (next_pg))

@user_login_required
def edit(request, objId):
    """Shows a specific Object for editing"""
    logging.debug('%s.%s - %s' % (request.resolver_match.namespaces,
                                  request.resolver_match.func.__name__, request.path))
    user = User.objects.logged_in(request.session)
    if user:
        cat = Cat.objects.get(id=objId)
        context = {'user': user,
                   'cat': cat, }
        return render(request, 'cats/edit_cat.html', context)
    else:
        # if not logged in send to login page with next page to go to after login
        next_pg = base64.urlsafe_b64encode(request.path)
        return redirect(reverse('users:disp_login') + '?next=%s' % (next_pg))


@user_login_required
def update(request, objId):
    """Updates a specific Object"""
    logging.debug('%s.%s - %s' % (request.resolver_match.namespaces,
                                  request.resolver_match.func.__name__, request.path))
    user = User.objects.logged_in(request.session)
    # need to move user owns cat validation to model
    cat = Cat.objects.get(id=objId)
    data = []
    if cat.user == user:
        # TODO add error handling
        valid, data = Cat.objects.update_cat(cat, request.POST)
        if valid:
            return redirect(reverse('cats:index'))
        else:
            for i in data:
                messages.add_message(request, messages.ERROR, i.message)
            return redirect(reverse('cats:edit', kwargs={'objId': cat.id}))
    else:
        # if not logged in send to login page with next page to go to after login
        messages.add_message(request, messages.ERROR, 'You are not the owner of the cat you just tried to edit')
        return redirect(reverse('cats:index', kwargs={'objId': cat.id}))

@user_login_required
def destroy(request, objId):
    """Deletes a specific Object"""
    logging.debug('%s.%s - %s' % (request.resolver_match.namespaces,
                                  request.resolver_match.func.__name__, request.path))
    user = User.objects.logged_in(request.session)
    cat = Cat.objects.get(id=objId)
    # Make sure the user is a valid user and the user owns the cat
    if cat.user == user:
        # TODO add error handling
        cat.delete()
        return redirect(reverse('cats:index'))
    else:
        # if not logged in send to login page with next page to go to after login
        messages.add_message(request, messages.ERROR, 'You are not the owner of the cat you just tried to delet')
        return redirect(reverse('cats:index'))

#need to validat user doesnt own cat
@user_login_required
def create_like(request, objId):
    logging.debug('%s.%s - %s' % (request.resolver_match.namespaces,
                                  request.resolver_match.func.__name__, request.path))
    user = User.objects.logged_in(request.session)
    cat = Cat.objects.get(id=objId)
    cat.likes.add(user)
    return redirect(reverse('cats:index'))


#need to validat user doesnt own cat
@user_login_required
def destroy_like(request, objId):
    logging.debug('%s.%s - %s' % (request.resolver_match.namespaces,
                                  request.resolver_match.func.__name__, request.path))
    user = User.objects.logged_in(request.session)
    cat = Cat.objects.get(id=objId)
    cat.likes.remove(user)
    return redirect(reverse('cats:index'))
  

apps/cats/templates/cats/_cat_fields.html
<div class="form-group">
  <label for="name">Name</label>
  <input type="text" class="form-control" name="name" id="name" aria-describedby="help_name" placeholder="" value="{{cat.name}}">
  <small id="help_name" class="form-text text-muted">Enter your cats name</small>
</div>
<div class="form-group">
  <label for="age">Age</label>
  <input type="number"
    class="form-control" name="age" id="age" aria-describedby="help_age" placeholder="" min="0" value="{{cat.age}}">
  <small id="help_age" class="form-text text-muted">Enter your cats age</small>
</div>

apps/cats/templates/cats/edit_cat.html
{% extends 'base.html' %} 
{% block title %} Edit a cat {% endblock title %} 
{% block content %}
<form action="{% url 'cats:update' cat.id %}" method="POST">
    {% csrf_token %}
    <h2>Edit {{cat.name}}</h2>
{% include '_flash_msgs.html' %}
    <div>
        {% include "cats/_cat_fields.html" %}
    </div>
    <button type="submit" class="btn btn-primary">Update!</button>
</form>
{% endblock content %}

apps/cats/templates/cats/list_cats.html
{% extends 'base.html' %} 
{% block title %} Welcome {% endblock title %} 
{% block content %}
{% include '_flash_msgs.html' %}
<h2>Welcom {{user.first_name}}!!</h2>
{% comment %} <a href="{% url 'cats:new'%}">Add a cat!</a> {% endcomment %}

<table class="table table-striped">
    <thead class="thead-inverse">
        <tr>
            <th>Name</th>
            <th>Age</th>
            <th>Likes</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        {% if cats %} {% for cat in cats %}
        <tr>
            <td scope="row"><a href="{% url 'cats:show' cat.id %}">{{cat.name}}</a></td>
            <td>{{cat.age}}</td>
            <td>{{cat.likes.count}}</td>
            <td>
                {% if cat.user == user %}
                    <a href="{% url 'cats:destroy' cat.id %}">delete</a> | <a href="{% url 'cats:edit' cat.id %}">edit</a>
                {% else %}
                    {% if user in cat.likes.all %}
                        <a href="{% url 'cats:destroy_like' cat.id %}">Remove Like</a>
                    {% else %}
                        <a href="{% url 'cats:create_like' cat.id %}">Add Like</a>
                    {% endif %}
                {% endif %}
                </td>
        </tr>
        {% endfor %} {% endif %}
    </tbody>
</table>
<!--<pre> {% filter force_escape %} {% debug %} {% endfilter %} </pre>-->
{% endblock content %}

apps/cats/templates/cats/new_cat.html
{% extends 'base.html' %} 
{% block title %} Add a cat {% endblock title %} 
{% block content %}
<form action="{% url 'cats:create' %}" method="POST">
    {% csrf_token %}
    <h2>Add a cat</h2>
{% include '_flash_msgs.html' %}
    <div>
        {% include "cats/_cat_fields.html" %}
    </div>
    <button type="submit" class="btn btn-primary">Add!</button>
</form>
{% endblock content %}

apps/cats/templates/cats/show_cat.html
{% extends 'base.html' %} 
{% block title %} {{cat.name}} details {% endblock title %} 
{% block content %}
<h2>{{cat.name}}!!</h2>
<p>Name: {{cat.name}}</p>
<p>Age: {{cat.age}}</p>
<p>Likes: {{cat.likes.count}}</p>
<!--<pre> {% filter force_escape %} {% debug %} {% endfilter %} </pre>-->
{% endblock content %}