Python_Cats_prj/urls.py
from django.conf.urls import url, include
# from django.contrib import admin

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^cats/', include('apps.cats.urls', namespace='cats')),
    # url(r'users/(?P<userId>\d+)/cats/', include('apps.cats.urls', namespace='user_cats')),
    url(r'^',include('apps.users.urls',namespace='users')),
]

apps/users/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.index),
    url(r'^login/$', views.show_login, name='disp_login'),
    url(r'^login/process/$', views.login, name='do_login'),
    url(r'^logout/$', views.logout, name='do_logout'),
    url(r'^combined/', views.show_register_login, name='disp_reg_login'),
    url(r'^register/', views.show_register, name='disp_reg'),
    url(r'^users/create/', views.create, name='create'),
    url(r'^users/list/$', views.show_users_list, name='disp_users'),
    url(r'^users/(?P<userId>\d+)/$', views.show, name='show'),
    url(r'^users/(?P<userId>)/edit/', views.edit, name='edit'),
    url(r'^users/(?P<userId>)/update/', views.edit, name='update'),
    url(r'^users/(?P<userId>)/destroy/', views.destroy, name='destroy'),
]

apps/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone
import isvalid
from error import Error
import bcrypt

# Create your models here.


class UserManager(models.Manager):
    def validate_registration(self, data):
        errors = []
        if 'first_name' in data and 'last_name' in data and 'email' in data and 'password' in data and 'c_password' in data:
            valid, msg = isvalid.first_name(data['first_name'])
            if not valid:
                errors.append(Error('first_name', msg))
            valid, msg = isvalid.last_name(data['last_name'])
            if not valid:
                errors.append(Error('last_name', msg))
            valid, msg = isvalid.email(data['email'])
            if not valid:
                errors.append(Error('email', msg))
            valid, msg = isvalid.password(
                data['password'], data['c_password'])
            if not valid:
                errors.append(Error('password', msg))
            # if all the fields look good make sure the user doesnt already exist
            if not errors:
                existing_users = self.filter(email=data['email'])
                if existing_users:
                    errors.append(Error(
                        'email', 'email already registered if you have forgoten your password please use the password reset link'))

        else:
            errors.append(
                Error('form', 'Something went wrong please try to submit the form again'))
        if errors:
            return (False, errors)
        else:

            return (True, data)

    def add(self, data):
        valid, errors = self.validate_registration(data)
        if valid:
            hashedpwd = bcrypt.hashpw(data['password'].encode(), bcrypt.gensalt())
            return (valid, self.create(first_name=data['first_name'],
                                       last_name=data['last_name'],
                                       email=data['email'],
                                       password=hashedpwd,))
        else:
            return (valid, errors)
    
    def authenticateUser(self, req, **kwargs):
        """Authenticate User"""
        pass

    def get_user(self, user_id):
        try:
            return self.get(id=user_id)
        except:
            return None

    def logged_in(self, ses):
        if 'user_id' in ses:
            try:
                user = self.get_user(ses['user_id'])
                return user
            except:
                return None
        return None

    def validateLogin(self, data):
        errors = []
        users = {}
        print 'in validate login'
        if 'email' in data and 'password' in data:
            valid, msg = isvalid.email(data['email'])
            if not valid:
                errors.append(Error('email', msg))
            # if the email looks good check if the user password matches
            if not errors:
                users = self.filter(email=data['email'])
                if len(users) > 1:
                    errors.append(Error('email, password', 'something went wrong please contact customer support'))
                else:
                    if bcrypt.hashpw(data['password'].encode(), users[0].password.encode()) != users[0].password:
                        errors.append(Error('email, password', 'incorrect email and password combination please try again'))
        else:
            errors.append(
                Error('form', 'Something went wrong please try to submit the form again'))
        if errors:
            return (False, errors)
        else:
            return (True, users[0])


class User(models.Model):
    objects = UserManager()
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.CharField(max_length=255)
    password = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '{}: {} {} {}'.format(self.id, self.first_name, self.last_name, self.email)

    def __unicode__(self):
        return '{}: {} {} {}'.format(self.id, self.first_name, self.last_name, self.email)

    @property
    def full_name(self):
        return '{} {}'.format(self.first_name, self.last_name)

    @property
    def is_authenticated(self):
        #if we have a user object to access this property then 
        #they are authenticated it should always be true
        return True

apps/users/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, HttpResponse, redirect
from django.views.decorators.http import require_http_methods
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.conf import settings
from .models import User
from .decorators import user_login_required
import base64
import logging
logging.basicConfig(level=logging.DEBUG,
                    format='%(asctime)s - %(levelname)s - %(message)s')

# Create your views here.

@user_login_required
def index(request):
    logging.debug(' %s. %s -  %s' % (request.resolver_match.namespaces,
                                      request.resolver_match.func.__name__, request.path))
    return redirect(settings.HOME_URL)
  

@user_login_required
def show_users_list(request):
    logging.debug(' %s. %s -  %s' % (request.resolver_match.namespaces,
                                      request.resolver_match.func.__name__, request.path))
    user = User.objects.get_user(request.session['user_id'])
    context = {'user': user,
                'users': User.objects.all()}
    return render(request, 'users/list.html', context)


def show_register(request):
    logging.debug(' %s. %s -  %s' % (request.resolver_match.namespaces,
                                      request.resolver_match.func.__name__, request.path))
    return render(request, 'users/register.html')


@require_http_methods(['POST'])
def create(request):
    logging.debug(' %s. %s -  %s' % (request.resolver_match.namespaces,
                                      request.resolver_match.func.__name__, request.path))
    valid, data = User.objects.add(request.POST)
    if valid:
        request.session['user_id'] = data.id
        return redirect(settings.HOME_URL)
    else:
        for i in data:
            messages.add_message(request, messages.ERROR, i.message)
    # can we do this better
    return redirect(reverse('users:disp_reg'))


def show_register_login(request):
    logging.debug(' %s. %s -  %s' % (request.resolver_match.namespaces,
                                      request.resolver_match.func.__name__, request.path))
    return render(request, 'users/combined.html')


def show_login(request):
    logging.debug(' %s. %s -  %s' % (request.resolver_match.namespaces,
                                      request.resolver_match.func.__name__, request.path))
    context =  {}
    if 'next' in request.GET:
        context['next_pg'] = request.GET['next']
    return render(request, 'users/login.html', context)


@require_http_methods(['POST'])
def login(request):
    logging.debug(' %s. %s -  %s' % (request.resolver_match.namespaces,
                                      request.resolver_match.func.__name__, request.path))
    """Validates user is email and password, sets session variables"""
    # flush the existing session if they were already logged in
    #request.session.flush()
    valid, data = User.objects.validateLogin(request.POST)
    if valid:
        # Move session to model?
        request.session['user_id'] = data.id
        print 'valid login'
        next_pg = settings.HOME_URL
        if 'next_pg' in request.POST and len(request.POST['next_pg']) > 0:
            print 'process next_pg'
            enc = request.POST['next_pg']
            next_pg = base64.urlsafe_b64decode(enc.encode('ascii'))
        print next_pg
        return redirect(next_pg)
    else:
        for i in data:
            messages.add_message(request, messages.ERROR, i.message)
        # TODO: looses next page if they type the password wrong
        return redirect('users:disp_login')

@user_login_required
def logout(request):
    logging.debug(' %s. %s -  %s' % (request.resolver_match.namespaces,
                                      request.resolver_match.func.__name__, request.path))
    request.session.flush()
    messages.add_message(request, messages.SUCCESS, 'You have been logged out')
    return redirect('users:disp_login')


def show(request, userId):
    logging.debug(' %s. %s -  %s' % (request.resolver_match.namespaces,
                                      request.resolver_match.func.__name__, request.path))
    user = User.objects.get(id=userId)
    reviews = user.reviews.all()

    context = {
        'user': user,
        'reviews': reviews,

    }
    return render(request, 'users/show_user.html', context)

@user_login_required
def edit(request, id):
    logging.debug(' %s. %s -  %s' % (request.resolver_match.namespaces,
                                      request.resolver_match.func.__name__, request.path))
    """Shows a specific Object for editing"""
    pass

@user_login_required
def update(request, id):
    logging.debug(' %s. %s -  %s' % (request.resolver_match.namespaces,
                                      request.resolver_match.func.__name__, request.path))
    """Updates a specific Object"""
    pass

@user_login_required
def destroy(request, id):
    logging.debug(' %s. %s -  %s' % (request.resolver_match.namespaces,
                                      request.resolver_match.func.__name__, request.path))
    """Deletes a specific Object"""
    pass

apps/users/templates/users/_login.html
<form action="{% url 'users:do_login' %}" method="POST">
    {% csrf_token %}
    <h2>Login</h2>
{% include '_flash_msgs.html' %}
    <input type="hidden" name="next_pg" value="{{ next_pg }}" />
    <div class="form-group">
        <label for="email">Email:</label>
        <input type="email" class="form-control" name="email" id="email" aria-describedby="email_help" placeholder="Enter your email">
        <small id="email_help" class="form-text text-muted">Enter your email</small>
    </div>
    <div class="form-group">
        <label for="password">Password:</label>
        <input type="password" class="form-control" name="password" id="password" placeholder="">
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>

apps/users/templates/users/_register.html
<form action="{% url 'users:create' %}" method="POST">
    {% csrf_token %}
    <h2>Registration</h2>
{% include '_flash_msgs.html' %}
    <div class="form-group">
        <label for="first_name">First Name:</label>
        <input type="text" class="form-control" name="first_name" id="first_name" aria-describedby="first_name_help" placeholder="Enter your first name">
        <small id="first_name_help" class="form-text text-muted">Enter your first name</small>
    </div>
    <div class="form-group">
        <label for="last_name">Last Name:</label>
        <input type="text" class="form-control" name="last_name" id="last_name" aria-describedby="last_name_help" placeholder="Enter your last name">
        <small id="last_name_help" class="form-text text-muted">Enter your last name</small>
    </div>
    <div class="form-group">
        <label for="email">Email:</label>
        <input type="email" class="form-control" name="email" id="email" aria-describedby="email_help" placeholder="Enter your email">
        <small id="email_help" class="form-text text-muted">Enter your email</small>
    </div>
    <div class="form-group">
        <label for="password">Password:</label>
        <input type="password" class="form-control" name="password" id="password" placeholder="">
    </div>
    <div class="form-group">
        <label for="c_password">Confirm Password:</label>
        <input type="password" class="form-control" name="c_password" id="c_password" placeholder="">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

apps/users/templates/users/combined.html
{% extends 'base.html' %} 
{% block title %}Register/Login{% endblock title %}
{% block content %} 
    <div class="">
    {% include "./_register.html" %} 
    {% include "./_login.html" %} 
    </div>

{% endblock content %}

apps/users/templates/users/list.html
{% extends 'base.html' %} {% block content %}
<table class="table table-striped">
    <thead class="thead-inverse">
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Password</th>
            <th>Date Added</th>

        </tr>
    </thead>
    <tbody>
        {% if users %} {% for user in users %}
        <tr>
            <td scope="row">{{user.first_name}}</td>
            <td>{{user.last_name}}</td>
            <td>{{user.email}}</td>
            <td>{{user.password}}</td>
            <td>{{user.created_at|date:"SHORT_DATETIME_FORMAT"}}</td>
        </tr>
        {% endfor %} {% endif %}
    </tbody>
</table>
<!--<pre> {% filter force_escape %} {% debug %} {% endfilter %} </pre>-->
{% endblock content %}

apps/users/templates/users/login.html
{% extends 'base.html' %} 
{% block title %}Login{% endblock title %}
{% block content %}
{% include "./_login.html" %} 
{% endblock content %}

apps/users/templates/users/register.html
{% extends 'base.html' %} 
{% block title %}Register{% endblock title %}
{% block content %}
{% include "./_register.html" %} 
{% endblock content %}

apps/users/templates/users/show_user.html
{% extends 'base.html' %} {% block content %}

<h2>User Alias: {{user.first_name}}</h2>
<div class="form-group">
  <label>Name:</label>
  <span class="form-control-static">{{ user.full_name }}</span>
</div>
<div class="form-group">
  <label>Email:</label>
  <span class="form-control-static">{{ user.email }}</span>
</div>
<div class="form-group">
  <label>Total Reviews:</label>
  <span class="form-control-static">{{ reviews.count }}</span>
</div>

<!--<pre> {% filter force_escape %} {% debug %} {% endfilter %} </pre>-->
{% endblock content %}