Python_Cats_prj/urls.py
from django.conf.urls import url, include
# from django.contrib import admin

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^cats/', include('apps.cats.urls', namespace='cats')),
    # url(r'users/(?P<userId>\d+)/cats/', include('apps.cats.urls', namespace='user_cats')),
    url(r'^',include('apps.users.urls',namespace='users')),
]

apps/cats/urls.py
from django.conf.urls import url
from . import views
import logging
logging.basicConfig(level=logging.DEBUG,
                    format='%(asctime)s - %(levelname)s - %(message)s')


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^new/$', views.new, name='new'),
    url(r'^create/$', views.create, name='create'),
    url(r'^(?P<objId>\d+)/$', views.show, name='show'),
    url(r'^(?P<objId>\d+)/edit/$', views.edit, name='edit'),
    url(r'^(?P<objId>\d+)/update/$', views.update, name='update'),
    url(r'^(?P<objId>\d+)/destroy/$', views.destroy, name='destroy'),
    url(r'^(?P<objId>\d+)/like/$', views.create_like, name='create_like'),
    url(r'^(?P<objId>\d+)/like/destroy$', views.destroy_like, name='destroy_like'),
]

apps/users/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.index),
    url(r'^login/$', views.show_login, name='disp_login'),
    url(r'^login/process/$', views.login, name='do_login'),
    url(r'^logout/$', views.logout, name='do_logout'),
    url(r'^combined/', views.show_register_login, name='disp_reg_login'),
    url(r'^register/', views.show_register, name='disp_reg'),
    url(r'^users/create/', views.create, name='create'),
    url(r'^users/list/$', views.show_users_list, name='disp_users'),
    url(r'^users/(?P<userId>\d+)/$', views.show, name='show'),
    url(r'^users/(?P<userId>)/edit/', views.edit, name='edit'),
    url(r'^users/(?P<userId>)/update/', views.edit, name='update'),
    url(r'^users/(?P<userId>)/destroy/', views.destroy, name='destroy'),
]

templates/_flash_msgs.html
 {% if messages %}
<div class="alert alert-danger">
    <ul class="messages">
        {% for msg in messages %}
        <li>{{msg.message}}</li>
        {% endfor %}
    </ul>
</div>
{% endif %}

templates/base.html
<!doctype html>
<html lang="en">
    {% load static %}
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ"
            crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/base_style.css' %}">
    </head>

    <body>
         {% if request.session.user_id %}
            <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                
                <a class="navbar-brand" href="{% url 'cats:index' %}">Home</a>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'cats:new' %}">Add a Cat </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:do_logout' %}">Logout</a>
                        </li>
                    </ul>
                </div>
            </nav>
          
        {% endif %}
            
        <div class="container wrap">
            {% block content %}{% endblock %}
        </div>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn"
            crossorigin="anonymous"></script>

        <!--<script src="{% static 'js/scripts.js' %}"></script>-->

    </body>

</html>